config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  root 'projects#index'
  resources :projects do
    resources :rewards
  end

  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
require 'date'

class Project < ActiveRecord::Base
  has_many :rewards
  belongs_to :user
  has_many :tags, as: :taggable
  # has_many :rewards, as: :rewardable

  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

def countdown
  startdate = Time.now
   (((self.end_date - startdate).to_i / 60) / 60) / 24
end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  # belongs_to :rewardable, polymorphic: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :rewards, through: :projects
  has_many :projects
  has_many :tags, as: :taggable

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  # before_action :require_login

# private
#   def current_user
#      @current_user ||= User.find(session[:user_id]) if session[:user_id]
#     end
#
#     helper_method :current_user
#
#     def ensure_logged_in
#       unless current_user
#         flash[:alert] = "Please log in"
#         redirect_to sessions_new_path
#       end
#     end

# private
# def not_authenticated
#   redirect_to login_path, alert: "Please login first"
# end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = if params[:search]
      Project.where("LOWER(title) LIKE LOWER(?)", "%#{params[:search]}%") # This is a query into the database
    else
    Project.all
    end

    respond_to do |format|
      format.html
      format.js
    end
  end
  def new
    # if cureent_user.admin? || current_user.vetted?
    @project = Project.new
    # else
    # redirect_to root_path
  end
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to projects_path, notice: "Project successfullly created!"
    else
      render :new
    end
  end

  def show
      @project = Project.find(params[:id])
      @rewards = @project.rewards.build
  end

  private

  def project_params
    params.require(:project)
          .permit(:title, :description, :goal, :end_date, :category,
                  rewards_attributes: [:title, :description, :amount, :_destroy])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to projects_path, notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to projects_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]

  def index
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # if @user.save
    #   redirect_to root_path, notice: "You have successfully signed up!"
    if @user.save
      redirect_to(:users, notice: 'User was successfully created')
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="styles.scss">
</head>
<body>

  <div id="navigation">
    <h1>Crowdfunder</h1>
      <div class="user_info">
        <% if current_user %>
          <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
          <%= link_to "Logout", :logout, method: :post %>
        <% else %>
          <%= link_to "Register", new_user_path %> |
          <%= link_to "Login", :login %>
        <% end %>
      </div>
  </div>

  <div>
    <span id="notice"><%= flash[:notice] %></span>
    <span id="alert"><%= flash[:alert] %></span>
  </div>

<%= yield %>

</body>
</html>

app/views/projects/_project.html.erb
    <ul>
      <li><%= link_to 'See Project', "projects/#{project.id}" %></li>
      <li>Project Title: <%= project.title %></li>
      <li>Goal: <%= number_to_currency(project.goal) %></li>
      <li>Ends in: <%= project.countdown %> days</li>
    </ul>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <%= link_to_remove_association "Remove reward", f %>

</div>

app/views/projects/index.html.erb
<div id="projects_container">

<div id="feature">
  <%= link_to 'New Project', new_project_path %><br>

  <%= form_tag projects_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
  <% end %>
</div>

<h1>Projects List</h1>

<div id="projects_results">
  <%= render @projects %>
</div>

<%= link_to 'All Projects', projects_path %>
</div>

app/views/projects/index.js.erb
$('#projects_results').html('<%= j(render @projects) %>');

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for @project do |f| %>

  <div class="field">
    <%= f.label :category %>
    <%= f.select :category, ['Music', 'Comic', 'Car', 'Technology', 'Design', 'Art', 'Sport', 'Finance', 'Food'], prompt: 'Select One' %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :goal %>
    <%= f.number_field :goal %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <h2>Rewards</h2>
  <div id="rewards">
  <%= f.fields_for :rewards do |reward_fields| %>
    <%= render 'reward_fields', f: reward_fields %>
  <% end %>

    <div class="link">
      <%= link_to_add_association "Add Reward", f, :rewards %>
    </div>
  </div>

  <div class="action">
    <%= f.submit "Create Project" %>
  </div>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<h2><%= @project.category %> Category</h2>
<%= @project.title %><br>
<%= @project.description %><br>
<%= @project.end_date %><br>
<%= "$#{@project.goal}" %><br>
<%= @project.backer_count %>0 Backers<br>
<%= @project.pledge_amount %>0 Pledged<br>
<%= "#{@project.countdown} Days" %>
<br>


<% @project.rewards.order(amount: :asc).each do |reward| %>
  <ul>
    <h3> Reward </h3>
    <em> <%= reward.title %> </em>
    <li> <%= "$#{reward.amount}" %> </li>
    <li> <%= reward.description %> </li>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<div class="field">
   <%= f.label :name %><br />
   <%= f.text_field :name %>
</div>
<div class="field">
   <%= f.label :email %><br />
   <%= f.email_field :email %>
</div>
<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>
<div class="action">
   <%= f.submit "Sign me up!" %><br />
</div>

<% end %>

app/views/users/new.html.erb
<%= render 'form' %>